# Generated by Django 5.0.2 on 2024-03-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_info_delete_userinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="member_id",
            new_name="id_str",
        ),
    ]
