# Generated by Django 5.0.2 on 2024-03-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_rename_member_id_info_id_str"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="id_str",
            new_name="member_id",
        ),
    ]
