# Generated by Django 5.0.2 on 2024-03-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_course_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                through="myapp.StudentSelectCourse", to="myapp.student"
            ),
        ),
    ]
