# Generated by Django 5.0.2 on 2024-03-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_course_students"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentSelectCourse",
            new_name="CourseSelection",
        ),
    ]
